// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK2CiKyo_deiQ1lgxlKHirO-jmKso4iNs',
    appId: '1:998184060954:web:903464cead16336f3d29a3',
    messagingSenderId: '998184060954',
    projectId: 'watchhub-app-df392',
    authDomain: 'watchhub-app-df392.firebaseapp.com',
    storageBucket: 'watchhub-app-df392.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxuNGaKmO6Fp2-5uOE_bE7maFHE-bZAWc',
    appId: '1:998184060954:android:f30f37a1f9f9ee6a3d29a3',
    messagingSenderId: '998184060954',
    projectId: 'watchhub-app-df392',
    storageBucket: 'watchhub-app-df392.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGRxvF0M1H_81UJ1K4LhoIJEyNRSrWr2g',
    appId: '1:998184060954:ios:e1c62cebc1dcea713d29a3',
    messagingSenderId: '998184060954',
    projectId: 'watchhub-app-df392',
    storageBucket: 'watchhub-app-df392.firebasestorage.app',
    iosBundleId: 'com.watchhub.watchhubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGRxvF0M1H_81UJ1K4LhoIJEyNRSrWr2g',
    appId: '1:998184060954:ios:e1c62cebc1dcea713d29a3',
    messagingSenderId: '998184060954',
    projectId: 'watchhub-app-df392',
    storageBucket: 'watchhub-app-df392.firebasestorage.app',
    iosBundleId: 'com.watchhub.watchhubApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK2CiKyo_deiQ1lgxlKHirO-jmKso4iNs',
    appId: '1:998184060954:web:633d1cf19e96bf3c3d29a3',
    messagingSenderId: '998184060954',
    projectId: 'watchhub-app-df392',
    authDomain: 'watchhub-app-df392.firebaseapp.com',
    storageBucket: 'watchhub-app-df392.firebasestorage.app',
  );
}
